### ISSUE TITLE
Add a screenshot test and add to travis CI 

### ISSUE THREAD

**Issue by mattab** [PiwikPRO/plugin-SimplePageBuilder#1]
it would be nice for this feature to plugin to include UI test that takes a screenshot only for the content of the page (this will check that the controller/view /replace thing works all at once and easy to troubleshoot)

See eg. a simple example: https://github.com/PiwikPRO/plugin-InterSites/blob/master/tests/UI/CompareCommonVisitors_spec.js

**Comment by mnapoli** [comment]
Has been done in 4bc8acebfb1240624af4e3000545176f434bddcd
